name: "Setup uv"
description: "Installs uv, and sets up Python environment"


inputs:
  python-version:
    description: "Python version to use"
    default: "3.x"


runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

