name: Ruff Style Check

on:
  pull_request:
    types: [ opened, synchronize, reopened, auto_merge_enabled ]
    paths:
      - "**/*.py"

jobs:
  lint:
    name: Ruff Style Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
    steps:
      - name: Check out the code at a specific ref
        uses: actions/checkout@v4

      - name: "Setup Environment"
        uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project, validate lockfile
        run: uv sync --locked --all-packages --all-extras --dev

      - name: Ruff format
        run: uv run ruff format --check
