name: Ruff Style Check

on:
  pull_request:
    types: [ opened, synchronize, reopened, auto_merge_enabled ]
    paths:
      - "**/*.py"

jobs:
  lint:
    name: Ruff Style Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
    steps:
      - name: Check out the code at a specific ref
        uses: actions/checkout@v4

      - name: "Setup Environment"
        uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies (including dev)
        run: uv sync --frozen --dev

      - name: Run Ruff Check
        run: uv run --only-dev ruff check --output-format=github .
